-- Insertar Monumentos
INSERT INTO monumento (codigo_pais, nombre_pais, nombre_ciudad, localizacion, nombre_monumento, descripcion, url_foto) VALUES ( 'ES', 'España', 'Barcelona', '41.4036, 2.1744', 'Sagrada Familia', 'Basílica diseñada por Antoni Gaudí, obra maestra del modernismo catalán iniciada en 1882 y aún en construcción.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Sagrada_Familia_8-12-21_%281%29.jpg/800px-Sagrada_Familia_8-12-21_%281%29.jpg');

INSERT INTO monumento (codigo_pais, nombre_pais, nombre_ciudad, localizacion, nombre_monumento, descripcion, url_foto) VALUES ( 'FR', 'Francia', 'París', '48.8584, 2.2945', 'Torre Eiffel', 'Estructura de hierro construida en 1889 para la Exposición Universal, símbolo icónico de París con 330 metros de altura.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Tour_Eiffel_Wikimedia_Commons.jpg/800px-Tour_Eiffel_Wikimedia_Commons.jpg');

INSERT INTO monumento (codigo_pais, nombre_pais, nombre_ciudad, localizacion, nombre_monumento, descripcion, url_foto) VALUES ( 'IT', 'Italia', 'Roma', '41.8902, 12.4922', 'Coliseo Romano', 'Anfiteatro construido en el siglo I d.C., el mayor anfiteatro jamás construido, donde se celebraban combates de gladiadores.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Colosseo_2020.jpg/800px-Colosseo_2020.jpg');

INSERT INTO monumento (codigo_pais, nombre_pais, nombre_ciudad, localizacion, nombre_monumento, descripcion, url_foto) VALUES ( 'GB', 'Reino Unido', 'Londres', '51.5007, -0.1246', 'Big Ben', 'Icónica torre del reloj del Palacio de Westminster, construida en 1859, uno de los símbolos más reconocibles de Londres.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Clock_Tower_-_Palace_of_Westminster%2C_London_-_May_2007.jpg/800px-Clock_Tower_-_Palace_of_Westminster%2C_London_-_May_2007.jpg');
INSERT INTO monumento (codigo_pais, nombre_pais, nombre_ciudad, localizacion, nombre_monumento, descripcion, url_foto) VALUES ( 'EG', 'Egipto', 'Giza', '29.9792, 31.1342', 'Pirámides de Giza', 'Conjunto de tres pirámides construidas como tumbas faraónicas hace más de 4500 años, única maravilla antigua que permanece.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/All_Gizah_Pyramids.jpg/800px-All_Gizah_Pyramids.jpg');
INSERT INTO monumento (codigo_pais, nombre_pais, nombre_ciudad, localizacion, nombre_monumento, descripcion, url_foto) VALUES ('US', 'Estados Unidos', 'Nueva York', '40.6892, -74.0445', 'Estatua de la Libertad', 'Escultura neoclásica en Liberty Island, regalo de Francia en 1886, símbolo de libertad y democracia con 93 metros de altura.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Statue_of_Liberty_7.jpg/800px-Statue_of_Liberty_7.jpg');
INSERT INTO monumento (codigo_pais, nombre_pais, nombre_ciudad, localizacion, nombre_monumento, descripcion, url_foto) VALUES ( 'IN', 'India', 'Agra', '27.1751, 78.0421', 'Taj Mahal', 'Mausoleo de mármol blanco construido entre 1632 y 1653 por el emperador Shah Jahan, considerado joya del arte islámico.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Taj_Mahal%2C_Agra%2C_India_edit3.jpg/800px-Taj_Mahal%2C_Agra%2C_India_edit3.jpg');
INSERT INTO monumento (codigo_pais, nombre_pais, nombre_ciudad, localizacion, nombre_monumento, descripcion, url_foto) VALUES ( 'CN', 'China', 'Beijing', '40.4319, 116.5704', 'Gran Muralla China', 'Sistema de fortificaciones construido entre el siglo V a.C. y siglo XVI, con más de 21.000 km de longitud total.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/The_Great_Wall_of_China_at_Jinshanling-edit.jpg/800px-The_Great_Wall_of_China_at_Jinshanling-edit.jpg');
INSERT INTO monumento (codigo_pais, nombre_pais, nombre_ciudad, localizacion, nombre_monumento, descripcion, url_foto) VALUES ( 'BR', 'Brasil', 'Río de Janeiro', '-22.9519, -43.2105', 'Cristo Redentor', 'Estatua Art Déco de Jesús de 30 metros de altura inaugurada en 1931, situada en la cima del cerro del Corcovado.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Christ_the_Redeemer_-_Cristo_Redentor.jpg/800px-Christ_the_Redeemer_-_Cristo_Redentor.jpg');
INSERT INTO monumento (codigo_pais, nombre_pais, nombre_ciudad, localizacion, nombre_monumento, descripcion, url_foto) VALUES ('PE', 'Perú', 'Cuzco', '-13.1631, -72.5450', 'Machu Picchu', 'Ciudadela inca del siglo XV situada en los Andes peruanos a 2430 metros de altitud, redescubierta en 1911.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Machu_Picchu%2C_Peru.jpg/800px-Machu_Picchu%2C_Peru.jpg');